# Numpy

In [4]:
import numpy as np

# Creating Arrays

In [6]:
mylist = [1,2,3]
x = np.array(mylist)
x

array([1, 2, 3])

In [8]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [9]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [10]:
m.shape

(2, 3)

In [13]:
n = np.arange(0, 30, 2)
n 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [15]:
n = n.reshape(3, 5 )
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [17]:
o = np.linspace(0, 4, 9)
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [18]:
o.resize(3, 3)

In [19]:
o

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

In [21]:
np.ones((3, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [23]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [24]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [27]:
#대각행렬
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [29]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [31]:
np.repeat([1,2,3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [34]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [36]:
#합치기
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

# Operations

In [39]:
x + y

array([5, 7, 9])

In [44]:
x * y
y

array([4, 5, 6])

In [43]:
#매트릭스 곱
x.dot(y)

32

In [45]:
x

array([1, 2, 3])

In [46]:
y

array([4, 5, 6])

In [48]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [50]:
z.shape

(2, 3)

In [51]:
z.T 

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [52]:
z.dtype

dtype('int64')

In [53]:
z = z.astype('f')

In [54]:
z.dtype

dtype('float32')

In [55]:
a = np.array([-4, -2, 1, 3, 5])

In [56]:
a.sum()

3

In [57]:
a.max()

5

In [58]:
a.min()

-4

In [59]:
a.mean()

0.59999999999999998

In [61]:
a.std()

3.2619012860600183

In [62]:
#최대값의 위치
a.argmax()

4

In [63]:
#최솟값의 위치
a.argmin()

0

# Indexing / Slicing

In [67]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [68]:
s[0], s[4], s[0:3]

(0, 16, array([0, 1, 4]))

In [69]:
#마이너스는 뒤에부터
s[-1]

144

In [70]:
s[1:5]

array([ 1,  4,  9, 16])

In [71]:
s[-5: -2]

array([ 64,  81, 100])

In [77]:
#거꾸로 새기
#-5부터 거꾸로 -2개씩 뒤어넘어서 끝까지
s[-5 :: -2]
#-5부터 정방향으로 2개씩 뒤어넘어서 끝까지
s[-5::2]

array([ 64, 100, 144])

In [75]:
s[-5 :: -1]s

array([64, 49, 36, 25, 16,  9,  4,  1,  0])

In [107]:
r = np.arange(36)
r.resize(6, 6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [108]:
r[2, 2]

14

In [109]:
r[3, 3:6]

array([21, 22, 23])

In [110]:
r[-1, ::2]

array([30, 32, 34])

In [112]:
r[r>30]=30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [114]:
#Copying Data
r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [115]:
r2[:]= 0

In [116]:
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [119]:
r
#r도 같이 변함
#항상 주의해야됨

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [121]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [122]:
r_copy[:] = 10
print(r_copy)
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


# Iterating Over Arrays

In [123]:
test = np.random.randint(0, 10, (4, 3))
test

array([[4, 2, 9],
       [9, 5, 3],
       [3, 1, 7],
       [6, 8, 2]])

In [124]:
#row 루프 돔
for row in test:
    print(row)

[4 2 9]
[9 5 3]
[3 1 7]
[6 8 2]


In [125]:
for i, row in enumerate(test):
    print(i, row)

0 [4 2 9]
1 [9 5 3]
2 [3 1 7]
3 [6 8 2]


In [126]:
test2 = test**2
test2

array([[16,  4, 81],
       [81, 25,  9],
       [ 9,  1, 49],
       [36, 64,  4]])

In [128]:
for i, j in zip(test, test2):
    print(i, '+', j, '=', i+j)

[4 2 9] + [16  4 81] = [20  6 90]
[9 5 3] + [81 25  9] = [90 30 12]
[3 1 7] + [ 9  1 49] = [12  2 56]
[6 8 2] + [36 64  4] = [42 72  6]


NameError: name 'i' is not defined

In [4]:
import numpy as np

In [11]:
sanghyuk = np.arange(35)

In [12]:
sanghyuk.resize(6, 6)

In [23]:
sanghyuk

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34,  0]])

In [35]:
sanghyuk[0:3]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [33]:
sanghyuk[0:3, ::3]

array([[ 0,  3],
       [ 6,  9],
       [12, 15]])

In [34]:
sanghyuk[0:3, ::7]

array([[ 0],
       [ 6],
       [12]])

In [17]:
sanghyuk.reshape(36)[::7]

array([ 0,  7, 14, 21, 28,  0])

In [40]:
sungju = np.arange(35)

In [42]:
sungju.resize(6, 6)

In [43]:
sungju

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34,  0]])

In [53]:
sungju[[2,3], [2, 3]]
sungju[2:4, 2:4]


array([[14, 15],
       [20, 21]])

In [55]:
sungju[:, ::7]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [57]:
sungju.reshape(36)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34,  0])